-- MySQL Script generated by MySQL Workbench
-- Fri Feb 10 21:08:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `STUDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `STUDENT` (
  `SID` INT NOT NULL AUTO_INCREMENT,
  `LastName` VARCHAR(45) NULL,
  `FirstName` VARCHAR(45) NULL,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` CHAR(2) NULL,
  `ZipCode` CHAR(5) NULL,
  `Class` CHAR(2) NULL,
  `HomeRoom` VARCHAR(45) NULL,
  `HomePhone` CHAR(10) NULL,
  PRIMARY KEY (`SID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Guardian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Guardian` (
  `PhoneNo` CHAR(10) NOT NULL,
  `GName` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`PhoneNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STUDENT_has_Guardian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `STUDENT_has_Guardian` (
  `STUDENT_SID` INT NOT NULL,
  `Guardian_PhoneNo` CHAR(10) NOT NULL,
  PRIMARY KEY (`STUDENT_SID`, `Guardian_PhoneNo`),
  INDEX `fk_STUDENT_has_Guardian_Guardian1_idx` (`Guardian_PhoneNo` ASC) VISIBLE,
  INDEX `fk_STUDENT_has_Guardian_STUDENT_idx` (`STUDENT_SID` ASC) VISIBLE,
  CONSTRAINT `fk_STUDENT_has_Guardian_STUDENT`
    FOREIGN KEY (`STUDENT_SID`)
    REFERENCES `STUDENT` (`SID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_STUDENT_has_Guardian_Guardian1`
    FOREIGN KEY (`Guardian_PhoneNo`)
    REFERENCES `Guardian` (`PhoneNo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MedInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MedInfo` (
  `STUDENT_SID` INT NOT NULL,
  `SequenceNo` INT NOT NULL,
  `Description` LONGTEXT NULL,
  PRIMARY KEY (`STUDENT_SID`, `SequenceNo`),
  CONSTRAINT `fk_MedInfo_STUDENT1`
    FOREIGN KEY (`STUDENT_SID`)
    REFERENCES `STUDENT` (`SID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TEACHER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEACHER` (
  `TID` CHAR(5) NOT NULL,
  `TNAME` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Salary` DECIMAL(8,2) NULL,
  PRIMARY KEY (`TID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COURSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COURSES` (
  `Subject` CHAR(4) NOT NULL,
  `CourseNo` CHAR(4) NULL,
  `Class` CHAR(2) NULL,
  `TEACHER_TID` CHAR(5) NOT NULL,
  `Room` CHAR(2) NULL,
  `Time` TIME NULL,
  PRIMARY KEY (`Subject`),
  INDEX `fk_COURSES_TEACHER1_idx` (`TEACHER_TID` ASC) VISIBLE,
  CONSTRAINT `fk_COURSES_TEACHER1`
    FOREIGN KEY (`TEACHER_TID`)
    REFERENCES `TEACHER` (`TID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STUDENT_has_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `STUDENT_has_Courses` (
  `STUDENT_SID` INT NOT NULL,
  `Courses_Subject` CHAR(4) NOT NULL,
  `Semester` CHAR(10) NULL,
  `Grade` CHAR(1) NULL,
  PRIMARY KEY (`STUDENT_SID`, `Courses_Subject`),
  INDEX `fk_STUDENT_has_Courses_Courses1_idx` (`Courses_Subject` ASC) VISIBLE,
  INDEX `fk_STUDENT_has_Courses_STUDENT1_idx` (`STUDENT_SID` ASC) VISIBLE,
  CONSTRAINT `fk_STUDENT_has_Courses_STUDENT1`
    FOREIGN KEY (`STUDENT_SID`)
    REFERENCES `STUDENT` (`SID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_STUDENT_has_Courses_Courses1`
    FOREIGN KEY (`Courses_Subject`)
    REFERENCES `COURSES` (`Subject`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ACTIVITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACTIVITY` (
  `AName` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`AName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TUITION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TUITION` (
  `PaymentID` CHAR(6) NOT NULL,
  `STUDENT_SID` INT NOT NULL,
  `Amount` INT NULL,
  `DatePaid` DATE NULL,
  PRIMARY KEY (`PaymentID`),
  INDEX `fk_TUITION_STUDENT1_idx` (`STUDENT_SID` ASC) VISIBLE,
  CONSTRAINT `fk_TUITION_STUDENT1`
    FOREIGN KEY (`STUDENT_SID`)
    REFERENCES `STUDENT` (`SID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEGREE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEGREE` (
  `DegreeID` INT NOT NULL AUTO_INCREMENT,
  `Program` VARCHAR(20) NULL,
  `Level` VARCHAR(5) NULL,
  `University` VARCHAR(45) NULL,
  `TEACHER_TID` CHAR(5) NOT NULL,
  `DDate` DATE NULL,
  PRIMARY KEY (`DegreeID`),
  INDEX `fk_DEGREE_TEACHER1_idx` (`TEACHER_TID` ASC) VISIBLE,
  CONSTRAINT `fk_DEGREE_TEACHER1`
    FOREIGN KEY (`TEACHER_TID`)
    REFERENCES `TEACHER` (`TID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STUDENT_has_ACTIVITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `STUDENT_has_ACTIVITY` (
  `STUDENT_SID` INT NOT NULL,
  `ACTIVITY_AName` VARCHAR(15) NOT NULL,
  `Semester` CHAR(10) NULL,
  PRIMARY KEY (`STUDENT_SID`, `ACTIVITY_AName`),
  INDEX `fk_STUDENT_has_ACTIVITY_ACTIVITY1_idx` (`ACTIVITY_AName` ASC) VISIBLE,
  INDEX `fk_STUDENT_has_ACTIVITY_STUDENT1_idx` (`STUDENT_SID` ASC) VISIBLE,
  CONSTRAINT `fk_STUDENT_has_ACTIVITY_STUDENT1`
    FOREIGN KEY (`STUDENT_SID`)
    REFERENCES `STUDENT` (`SID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_STUDENT_has_ACTIVITY_ACTIVITY1`
    FOREIGN KEY (`ACTIVITY_AName`)
    REFERENCES `ACTIVITY` (`AName`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
